"use client";

import { useCallback, useEffect, useState, type FormEvent, type ReactNode } from "react";
import { AlertCircle, Building2, Loader2, MapPin, Plus, Send, Store, Trash2, X } from "lucide-react";
import { ApiError, apiFetch, RequireAuth } from "@parchemos/shared/auth";
import { PrimaryButton, SurfaceCard } from "@parchemos/shared/components";

type Status = "pendiente_aprobacion" | "activa" | "rechazada";
type Schedule = { id?: string; dayOfWeek: number; startsAt: string; endsAt: string };
type GalleryImage = { id: string; url: string };
type Location = { id: string; name: string; address: string; description: string | null; status: Status; rejectionReason: string | null; logoUrl: string | null; coverUrl: string | null; schedules: Schedule[]; images: GalleryImage[] };
type Restaurant = { id: string; businessName: string; locations: Location[] };
const DAYS = [{ label: "Lunes", value: 1 }, { label: "Martes", value: 2 }, { label: "Miércoles", value: 3 }, { label: "Jueves", value: 4 }, { label: "Viernes", value: 5 }, { label: "Sábado", value: 6 }, { label: "Domingo", value: 0 }];
const statusText: Record<Status, string> = { pendiente_aprobacion: "Pendiente de aprobación", activa: "Activa", rechazada: "Sin solicitud" };
const statusStyle: Record<Status, string> = { pendiente_aprobacion: "bg-amber-50 text-amber-700", activa: "bg-emerald-50 text-emerald-700", rechazada: "bg-gray-100 text-gray-600" };
const errorMessage = (error: unknown, fallback: string) => error instanceof ApiError ? error.message : fallback;

export function Restaurants() { return <RequireAuth loginPath="/login" allowedRoles={["restaurante"]}><Manager /></RequireAuth>; }

function Manager() {
  const [restaurants, setRestaurants] = useState<Restaurant[]>([]), [error, setError] = useState<string | null>(null), [busy, setBusy] = useState(false), [businessOpen, setBusinessOpen] = useState(false), [restaurantId, setRestaurantId] = useState<string | null>(null), [location, setLocation] = useState<Location | null>(null);
  const load = useCallback(async () => { try { setRestaurants(await apiFetch<Restaurant[]>("/restaurantes/mios")); } catch (e) { setError(errorMessage(e, "No pudimos cargar tus restaurantes.")); } }, []);
  useEffect(() => { void load(); }, [load]);
  const run = async (action: () => Promise<void>, fallback: string): Promise<boolean> => { setBusy(true); setError(null); try { await action(); await load(); return true; } catch (e) { setError(errorMessage(e, fallback)); return false; } finally { setBusy(false); } };
  const createBusiness = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const businessName = String(new FormData(event.currentTarget).get("businessName")).trim(); await run(async () => { await apiFetch("/restaurantes", { method: "POST", body: { businessName } }); setBusinessOpen(false); }, "No pudimos crear el restaurante."); };
  const createLocation = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!restaurantId) return; const form = new FormData(event.currentTarget); const description = String(form.get("description")).trim(); const body = { name: String(form.get("name")).trim(), address: String(form.get("address")).trim(), ...(description ? { description } : {}) }; await run(async () => { await apiFetch(`/restaurantes/${restaurantId}/sedes`, { method: "POST", body }); setRestaurantId(null); }, "No pudimos crear la sede."); };
  return <main className="min-h-full bg-gray-50 px-4 py-6"><div className="mx-auto max-w-5xl"><header className="mb-6 flex items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-wider text-primary">Panel de negocio</p><h1 className="text-2xl font-bold text-gray-900">Mis restaurantes</h1><p className="text-sm text-muted-foreground">Administra la información pública de cada sede.</p></div><PrimaryButton onClick={() => setBusinessOpen(true)}><Plus className="h-4 w-4" />Añadir restaurante</PrimaryButton></header>{error && <Alert text={error} close={() => setError(null)} />}<div className="grid gap-4 md:grid-cols-2">{restaurants.map(restaurant => <SurfaceCard key={restaurant.id} className="bg-white"><div className="p-5"><div className="flex gap-3"><Building2 className="h-8 w-8 text-primary" /><div><h2 className="font-semibold">{restaurant.businessName}</h2><p className="text-xs text-muted-foreground">{restaurant.locations.length} sedes</p></div></div><div className="mt-4 space-y-2">{restaurant.locations.map(item => <button key={item.id} onClick={() => setLocation(item)} className="w-full rounded-xl border bg-gray-50 p-3 text-left hover:border-orange-300"><div className="flex justify-between gap-2"><b className="truncate text-sm">{item.name}</b><StatusBadge status={item.status} /></div><p className="mt-1 text-xs text-gray-500"><MapPin className="mr-1 inline h-3 w-3" />{item.address}</p>{item.rejectionReason && <p className="mt-1 text-xs text-red-600">{item.rejectionReason}</p>}</button>)}</div></div><button onClick={() => setRestaurantId(restaurant.id)} className="w-full border-t py-3 text-sm font-semibold text-primary">+ Añadir sede</button></SurfaceCard>)}</div>{!restaurants.length && <SurfaceCard className="mt-4 bg-white p-10 text-center"><Store className="mx-auto text-primary" /><p className="mt-2 text-sm">Crea tu empresa y registra una sede para comenzar.</p></SurfaceCard>}{businessOpen && <Modal title="Añadir restaurante" close={() => setBusinessOpen(false)}><form onSubmit={createBusiness}><Field label="Razón social" name="businessName" min={2} max={160} required /><Save busy={busy} label="Crear restaurante" /></form></Modal>}{restaurantId && <Modal title="Añadir sede" close={() => setRestaurantId(null)}><form onSubmit={createLocation}><Field label="Nombre de la sede" name="name" min={2} max={120} required /><Field label="Dirección" name="address" min={5} max={250} required /><Area label="Descripción (opcional)" name="description" max={2000} /><Save busy={busy} label="Crear sede" /></form></Modal>}{location && <Profile location={location} busy={busy} close={() => setLocation(null)} run={run} />}</div></main>;
}

function Profile({ location, busy, close, run }: { location: Location; busy: boolean; close: () => void; run: (action: () => Promise<void>, fallback: string) => Promise<boolean> }) {
  const [tab, setTab] = useState<"info" | "hours" | "images" | "preview">("info"), [draft, setDraft] = useState(location), [requestSuccess, setRequestSuccess] = useState(false);
  const saveInfo = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const description = String(form.get("description")).trim(); await run(async () => setDraft(await apiFetch<Location>(`/restaurantes/sedes/${draft.id}`, { method: "PATCH", body: { name: String(form.get("name")).trim(), address: String(form.get("address")).trim(), description } })), "No pudimos guardar; la información anterior se conserva."); };
  const saveHours = () => run(async () => { const schedules = draft.schedules.map(({ dayOfWeek, startsAt, endsAt }) => ({ dayOfWeek, startsAt, endsAt })); setDraft({ ...draft, schedules: await apiFetch<Schedule[]>(`/restaurantes/sedes/${draft.id}/horarios`, { method: "PUT", body: { schedules } }) }); }, "No pudimos guardar los horarios.");
  const saveImage = (kind: "logo" | "portada", url: string) => run(async () => setDraft(await apiFetch<Location>(`/restaurantes/sedes/${draft.id}/${kind}`, { method: "PUT", body: { url } })), "No pudimos guardar la imagen.");
  const addGallery = (url: string) => run(async () => { const image = await apiFetch<GalleryImage>(`/restaurantes/sedes/${draft.id}/galeria`, { method: "POST", body: { url } }); setDraft({ ...draft, images: [...draft.images, image] }); }, "No pudimos agregar la imagen.");
  const removeGallery = (id: string) => run(async () => { await apiFetch(`/restaurantes/sedes/${draft.id}/galeria/${id}`, { method: "DELETE" }); setDraft({ ...draft, images: draft.images.filter(image => image.id !== id) }); }, "No pudimos eliminar la imagen.");
  const requestApproval = async () => { const sent = await run(async () => setDraft(await apiFetch<Location>(`/restaurantes/sedes/${draft.id}/solicitud-autorizacion`, { method: "POST" })), "No pudimos enviar la solicitud."); setRequestSuccess(sent); };
  return <Modal title={draft.name} close={close} wide>{requestSuccess && <p role="status" className="mb-4 rounded-xl bg-emerald-50 px-3 py-2 text-sm text-emerald-700">Solicitud enviada con éxito. Quedó pendiente de aprobación.</p>}<nav className="mb-5 flex gap-4 border-b">{(["info", "hours", "images", "preview"] as const).map(key => <button key={key} onClick={() => setTab(key)} className={`pb-2 text-sm font-medium ${tab === key ? "border-b-2 border-primary text-primary" : "text-gray-500"}`}>{({ info: "Información", hours: "Horarios", images: "Imágenes", preview: "Vista previa" })[key]}</button>)}</nav>{tab === "info" && <form onSubmit={saveInfo}><Field label="Nombre" name="name" min={2} max={120} required value={draft.name} /><Field label="Dirección" name="address" min={5} max={250} required value={draft.address} /><Area label="Descripción (opcional)" name="description" max={2000} value={draft.description ?? ""} /><Save busy={busy} label="Guardar información" /></form>}{tab === "hours" && <Hours schedules={draft.schedules} setSchedules={schedules => setDraft({ ...draft, schedules })} save={saveHours} busy={busy} />}{tab === "images" && <Images location={draft} busy={busy} saveImage={saveImage} addGallery={addGallery} removeGallery={removeGallery} />}{tab === "preview" && <Preview location={draft} />}<footer className="mt-5 flex items-center justify-between border-t pt-4"><StatusBadge status={draft.status} />{draft.status !== "activa" && <PrimaryButton disabled={busy || draft.status === "pendiente_aprobacion"} onClick={() => void requestApproval()}><Send className="h-4 w-4" />Solicitar autorización</PrimaryButton>}</footer></Modal>;
}

function Hours({ schedules, setSchedules, save, busy }: { schedules: Schedule[]; setSchedules: (items: Schedule[]) => void; save: () => void; busy: boolean }) { const byDay = (day: number) => schedules.find(item => item.dayOfWeek === day); const setDay = (day: number, patch: Partial<Schedule> | null) => { const existing = byDay(day); setSchedules(patch ? [...schedules.filter(item => item.dayOfWeek !== day), { dayOfWeek: day, startsAt: "09:00", endsAt: "18:00", ...existing, ...patch }] : schedules.filter(item => item.dayOfWeek !== day)); }; return <section><p className="mb-4 text-sm text-muted-foreground">Configura un horario por día. Desactiva el día cuando no atiendas.</p><div className="space-y-2">{DAYS.map(({ label, value }) => { const item = byDay(value), open = Boolean(item); return <div key={label} className="grid grid-cols-[1fr_auto_auto] items-center gap-3 rounded-xl border p-3"><label className="flex items-center gap-2 text-sm font-medium"><input type="checkbox" checked={open} onChange={e => setDay(value, e.target.checked ? {} : null)} />{label}</label><input type="time" disabled={!open} value={item?.startsAt ?? "09:00"} onChange={e => setDay(value, { startsAt: e.target.value })} className="rounded-lg border px-2 py-1 disabled:bg-gray-100" /><input type="time" disabled={!open} value={item?.endsAt ?? "18:00"} onChange={e => setDay(value, { endsAt: e.target.value })} className="rounded-lg border px-2 py-1 disabled:bg-gray-100" /></div>; })}</div><PrimaryButton onClick={save} disabled={busy} className="mt-4">{busy && <Loader2 className="h-4 w-4 animate-spin" />}Guardar horarios</PrimaryButton></section>; }

function Images({ location, busy, saveImage, addGallery, removeGallery }: { location: Location; busy: boolean; saveImage: (kind: "logo" | "portada", url: string) => Promise<boolean>; addGallery: (url: string) => Promise<boolean>; removeGallery: (id: string) => Promise<boolean> }) { const [success, setSuccess] = useState<string | null>(null); const submit = async (event: FormEvent<HTMLFormElement>, label: string, action: (url: string) => Promise<boolean>) => { event.preventDefault(); const url = String(new FormData(event.currentTarget).get("url")).trim(); if (await action(url)) setSuccess(`${label} guardada correctamente.`); }; const input = (label: string, action: (url: string) => Promise<boolean>) => <form onSubmit={e => void submit(e, label, action)} className="rounded-xl border p-3"><label className="mb-2 block text-sm font-medium">{label}</label><div className="flex gap-2"><input required name="url" type="url" pattern="https://.*" placeholder="https://imagen..." className="min-w-0 flex-1 rounded-lg border px-2 py-1.5 text-sm" /><PrimaryButton type="submit" disabled={busy}>Guardar</PrimaryButton></div></form>; return <section className="space-y-4">{success && <p role="status" className="rounded-xl bg-emerald-50 px-3 py-2 text-sm text-emerald-700">{success}</p>}{input("URL del logo", url => saveImage("logo", url))}{input("URL de la portada", url => saveImage("portada", url))}{input("URL para añadir a la galería", addGallery)}<div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{location.images.map(image => <div key={image.id} className="relative"><img src={image.url} alt="Galería" className="aspect-video w-full rounded-xl object-cover" /><button onClick={() => void removeGallery(image.id)} className="absolute right-1 top-1 rounded bg-white p-1"><Trash2 className="h-4 w-4 text-red-600" /></button></div>)}</div></section>; }
function Preview({ location }: { location: Location }) { return <div className="overflow-hidden rounded-xl border"><div className="h-40 bg-orange-100">{location.coverUrl && <img src={location.coverUrl} alt="Portada" className="h-full w-full object-cover" />}</div><div className="p-5"><div className="-mt-12 mb-3 h-16 w-16 overflow-hidden rounded-xl border-4 border-white bg-white">{location.logoUrl && <img src={location.logoUrl} alt="Logo" className="h-full w-full object-cover" />}</div><h3 className="font-bold">{location.name}</h3>{location.description && <p className="mt-1 text-sm">{location.description}</p>}<p className="mt-2 text-sm text-gray-600">{location.address}</p>{location.images.length > 0 && <div className="mt-3 grid grid-cols-3 gap-2">{location.images.map(image => <img key={image.id} src={image.url} alt="Galería" className="aspect-video w-full rounded object-cover" />)}</div>}</div></div>; }
function Modal({ title, close, children, wide = false }: { title: string; close: () => void; children: ReactNode; wide?: boolean }) { return <div className="fixed inset-0 z-50 overflow-auto bg-black/30 p-4"><SurfaceCard className={`mx-auto my-6 bg-white p-5 ${wide ? "max-w-3xl" : "max-w-md"}`}><div className="mb-4 flex justify-between"><h2 className="font-semibold">{title}</h2><button onClick={close}><X className="h-5 w-5" /></button></div>{children}</SurfaceCard></div>; }
function Field({ label, name, min, max, required, value }: { label: string; name: string; min: number; max: number; required: boolean; value?: string }) { const message = `${label} es obligatorio y debe tener entre ${min} y ${max} caracteres.`; return <label className="mb-3 block text-sm">{label}<input required={required} name={name} minLength={min} maxLength={max} defaultValue={value} onInvalid={event => { event.currentTarget.setCustomValidity(message); event.currentTarget.parentElement?.querySelector("small")?.removeAttribute("hidden"); }} onInput={event => { event.currentTarget.setCustomValidity(""); event.currentTarget.parentElement?.querySelector("small")?.setAttribute("hidden", "true"); }} className="mt-1 w-full rounded-xl border p-2.5" /><small hidden className="mt-1 block text-xs text-red-600">{message}</small></label>; }
function Area({ label, name, max, value }: { label: string; name: string; max: number; value?: string }) { return <label className="mb-3 block text-sm">{label}<textarea name={name} maxLength={max} defaultValue={value} rows={4} className="mt-1 w-full rounded-xl border p-2.5" /></label>; }
function Save({ busy, label }: { busy: boolean; label: string }) { return <PrimaryButton type="submit" disabled={busy}>{busy && <Loader2 className="h-4 w-4 animate-spin" />}{label}</PrimaryButton>; }
function StatusBadge({ status }: { status: Status }) { return <span className={`shrink-0 rounded px-2 py-1 text-xs ${statusStyle[status]}`}>{statusText[status]}</span>; }
function Alert({ text, close }: { text: string; close: () => void }) { return <div role="alert" className="fixed left-1/2 top-5 z-[60] flex w-[min(92vw,42rem)] -translate-x-1/2 justify-between rounded-xl bg-red-50 p-3 text-sm text-red-700 shadow-lg"><span><AlertCircle className="mr-2 inline h-4 w-4" />{text}</span><button onClick={close}><X className="h-4 w-4" /></button></div>; }
