export const moderationItems = [
  {
    id: 1,
    type: "post",
    author: "Carlos Mendoza",
    content: "El mejor lomo al trapo que he probado 🔥 El servicio en La Leña fue increíble, el maître Ricardo nos atendió perfectamente. Totalmente recomendado.",
    reports: 0,
    time: "hace 10 min",
    status: "pending",
    restaurant: "La Leña Parrilla",
  },
  {
    id: 2,
    type: "review",
    author: "María García",
    content: "Servicio pésimo. Esperamos 2 horas y el pedido llegó frío. No recomendable para nada. Solicito reembolso.",
    reports: 3,
    time: "hace 25 min",
    status: "reported",
    restaurant: "Trattoria Bacco",
  },
  {
    id: 3,
    type: "story",
    author: "Valentina Torres",
    content: "Historia: tarde de sushi en Nagoya 🍣✨",
    reports: 0,
    time: "hace 1h",
    status: "approved",
    restaurant: "Sushi Nagoya",
  },
  {
    id: 4,
    type: "comment",
    author: "Diego Rodríguez",
    content: "Este lugar es una completa estafa, cobran doble y el menú no tiene precios claros. ¡Cuidado con este sitio!",
    reports: 8,
    time: "hace 2h",
    status: "reported",
    restaurant: "Andrés Carne de Res",
  },
  {
    id: 5,
    type: "post",
    author: "Sebastián Gómez",
    content: "Nuevo restaurante en Chapinero que vale MUCHO la pena. Pedimos el menú degustación de 7 tiempos.",
    reports: 0,
    time: "hace 3h",
    status: "approved",
    restaurant: "Masa",
  },
];
