export const STATUS_COLORS: Record<string, string> = {
  active: "bg-emerald-50 text-emerald-700 border-emerald-100",
  inactive: "bg-gray-100 text-gray-500 border-gray-200",
  suspended: "bg-amber-50 text-amber-700 border-amber-100",
  blocked: "bg-red-50 text-red-700 border-red-100",
  verified: "bg-emerald-50 text-emerald-700 border-emerald-100",
  pending: "bg-amber-50 text-amber-700 border-amber-100",
  approved: "bg-emerald-50 text-emerald-700 border-emerald-100",
  reported: "bg-red-50 text-red-700 border-red-100",
  open: "bg-blue-50 text-blue-700 border-blue-100",
  in_progress: "bg-amber-50 text-amber-700 border-amber-100",
  escalated: "bg-red-50 text-red-700 border-red-100",
  closed: "bg-gray-100 text-gray-500 border-gray-200",
  completed: "bg-emerald-50 text-emerald-700 border-emerald-100",
  failed: "bg-red-50 text-red-700 border-red-100",
  refunded: "bg-purple-50 text-purple-700 border-purple-100",
  reviewing: "bg-blue-50 text-blue-700 border-blue-100",
  pending_docs: "bg-amber-50 text-amber-700 border-amber-100",
  ready: "bg-emerald-50 text-emerald-700 border-emerald-100",
  scheduled: "bg-blue-50 text-blue-700 border-blue-100",
  ended: "bg-gray-100 text-gray-500 border-gray-200",
  critical: "bg-red-50 text-red-700 border-red-100",
  warning: "bg-amber-50 text-amber-700 border-amber-100",
  info: "bg-blue-50 text-blue-700 border-blue-100",
  high: "bg-red-50 text-red-700 border-red-100",
  medium: "bg-amber-50 text-amber-700 border-amber-100",
  low: "bg-gray-100 text-gray-500 border-gray-200",
};

export const STATUS_LABELS: Record<string, string> = {
  active: "Activo",
  inactive: "Inactivo",
  suspended: "Suspendido",
  blocked: "Bloqueado",
  verified: "Verificado",
  pending: "Pendiente",
  approved: "Aprobado",
  reported: "Reportado",
  open: "Abierto",
  in_progress: "En progreso",
  escalated: "Escalado",
  closed: "Cerrado",
  completed: "Completado",
  failed: "Fallido",
  refunded: "Reembolsado",
  reviewing: "En revisión",
  pending_docs: "Docs. pendientes",
  ready: "Listo",
  scheduled: "Programada",
  ended: "Finalizada",
  critical: "Crítico",
  warning: "Advertencia",
  info: "Info",
  high: "Alta",
  medium: "Media",
  low: "Baja",
};
